name: esade-topic-analysis-twitter
dependencies:
- gensim=3.8.3
- matplotlib=3.3.4
- nltk=3.4.5
- pyldavis=2.1.2
- python=3.7.1
- pandas=1.1.0
- scikit-learn=0.24.1
- wordcloud=1.8.1
- pip:
    - ipykernel==5.3.4
    - ipython==7.10.0
channels:
- conda-forge
